name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: backend/environment.yml  
        activate-environment: yccp
        auto-activate-base: false
        shell-setup: true

    - name: Install pylint
      shell: bash -l {0}
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate yccp
        conda install -y pylint

    - name: Analyzing the code with pylint
      shell: bash -l {0}
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate yccp
        pylint $(git ls-files '*.py')