name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: backend/environment.yml  
        auto-activate-base: false

    - name: Initialize Conda and activate environment
      shell: bash -l {0}
      run: |
        conda init bash  # Initialize conda for bash shell
        source ~/.bashrc  # Source the updated bashrc to apply conda init
        conda activate yccp  # Activate the environment with the name defined in environment.yml
        python -m pip install pylint  # Install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')